spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecnutradesystemdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dinghuaye521

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换


